language: node.js
node_js:
  - "14"

install:
  - npm install -g serverless
  - travis_retry npm install

before_install: cd backend

script:
  - serverless config credentials --provider aws --key "$AWS_ACCESS_KEY_ID" --secret "$AWS_SECRET_ACCESS_KEY" --sessionToken "$AWS_SESSION_TOKEN" --profile "$AWS_PROFILE"
  - serverless plugin install -n serverless-webpack
  - serverless deploy --aws-profile "$AWS_PROFILE"